### ISSUE TITLE
Bug: 开黑啦调用失败

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi-plugin-marry#1]
### Describe the bug

日志报错 `TypeError: Cannot read properties of undefined (reading 'map')  at KookBot.getGuildMemberList `
上下文无返回信息

### Steps to reproduce

配置好适配器与插件后，在频道内输入 marry，查看日志

### Expected behavior

可以在开黑啦频道内正常使用 marry 命令

### Relevant log output

```shell
2023-01-07 17:56:02 [W] command marry 
                        TypeError: Cannot read properties of undefined (reading 'map')
                            at KookBot.getGuildMemberList (D:\workspace\koishi\cy10000\node_modules\@satorijs\adapter-kook\lib\index.js:627:18)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async couple.setMemberList (D:\workspace\koishi\cy10000\node_modules\koishi-plugin-marry\lib\couple.js:48:33)
                            at async couple.getMemberList (D:\workspace\koishi\cy10000\node_modules\koishi-plugin-marry\lib\couple.js:56:116)
                            at async couple.getCouple (D:\workspace\koishi\cy10000\node_modules\koishi-plugin-marry\lib\couple.js:81:33)
                            at async _Command.<anonymous> (D:\workspace\koishi\cy10000\node_modules\koishi-plugin-marry\lib\index.js:38:29)
                            at async Array.<anonymous> (D:\workspace\koishi\cy10000\node_modules\@koishijs\core\lib\index.cjs:1512:14)
                            at async _Command.execute (D:\workspace\koishi\cy10000\node_modules\@koishijs\core\lib\index.cjs:1527:22)
                            at async D:\workspace\koishi\cy10000\node_modules\@koishijs\core\lib\index.cjs:2052:22
                            at async Session.withScope (D:\workspace\koishi\cy10000\node_modules\@koishijs\core\lib\index.cjs:1935:14)
```

### Launcher

yarn start

### Versions

1.2.0
- Koishi version: 4.11.0

**Comment by Seidko** [comment]
好像是kook adapter的问题，我去看看。

**Comment by Seidko** [comment]
@MirrorCY 已修复，等待上游合并即可。
