### ISSUE TITLE
Bug: 发生未知错误

### ISSUE THREAD

**Issue by JstzjgscSergino** [koishijs/koishi-plugin-marry#7]
### Describe the bug

载入marry插件后，在qq中输入“marry”却会返回“发生未知错误”。

### Steps to reproduce

下载安装marry插件；
启动插件；
在QQ中输入“marry”。

### Expected behavior

能正常使用。

### Screenshots

![QQ截图20230420101423](https://user-images.githubusercontent.com/120247122/233240935-3bbc61a2-05dc-4605-a8f3-52c775580e08.png)

### Relevant log output

```shell
1000|2|2023-04-20 10:13:29 [I] app apply plugin marry:fla79p
1000|2|2023-04-20 10:13:29 [W] app Error
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:143:
1000|2|                            at $b (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:1:228)
1000|2|                            at initSqlJs (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:22:24)
1000|2|                            at new Promise (<anonymous>)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs::20
1000|2|                            at SQLiteDriver.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:2:)
1000|2|                            at ForkScope.ensure (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:257:18)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:40
1000|2|                            at Context.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:619:)
1000|2|                            at Lifecycle.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:21)
1000|2|                            at $b (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:1:228)
1000|2|2023-04-20 10:13:29 [W] app Error
1000|2|                            at new Promise (<anonymous>)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:143:
1000|2|                            at SQLiteDriver.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:2:)
1000|2|                            at initSqlJs (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:22:24)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:40
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs::20
1000|2|                            at Lifecycle.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:21)
1000|2|                            at ForkScope.ensure (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:257:18)
1000|2|                            at Context.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:619:)
1000|2|2023-04-20 10:13:29 [W] sqlite > UPDATE `marry_data_v2` SET `value` = '1681956809540' WHERE `key` = 'latestCleanUpTime'
1000|2|                            at $b (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:1:228)
1000|2|2023-04-20 10:13:29 [W] app Error
1000|2|                            at new Promise (<anonymous>)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:143:
1000|2|                            at SQLiteDriver.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:2:)
1000|2|                            at initSqlJs (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:22:24)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:40
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs::20
1000|2|                            at Lifecycle.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:162:21)
1000|2|                            at ForkScope.ensure (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:257:18)
1000|2|2023-04-20 10:13:29 [W] app Error: unable to open database file
1000|2|                            at Context.start (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:619:)
1000|2|                            at c.step (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:81:)
1000|2|                            at f.handleError (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::80
1000|2|                            at c.run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:84:116)
1000|2|                            at SQLiteDriver.#run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::41)
1000|2|                            at SQLiteDriver.#exec (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::20)
1000|2|                            at SQLiteDriver.set (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::49)
1000|2|                            at SQLiteDriver.#update (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::)
1000|2|                            at async cleanUpMarriages (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-marry\lib\couple.js::17)
1000|2|                            at async DatabaseService.set (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:572:5)
1000|2|2023-04-20 10:15:48 [W] sqlite > UPDATE `stats_daily` SET `command` = '{"status":6,"echo":2,"dvc":28,"jrrp":3,"marry":2}',`botSend` = '{"onebot:2224":68,"sandbox:d1z79ctl:koishi":2}',`botReceive` = '{"onebot:2224":252,"sandbox:d1z79ctl:koishi":4}',`group` = '{"onebot:477":50,"sandbox:d1z79ctl:#":1,"onebot:289772519":18}' WHERE `time` = 1681920000000
1000|2|2023-04-20 10:15:48 [W] sqlite > INSERT INTO `stats_hourly` (`total`, `group`, `private`, `command`, `dialogue`, `time`) VALUES (4, 4, 0, 3, 0, 1681956000000)
1000|2|2023-04-20 10:15:48 [W] sqlite > UPDATE `stats_longterm` SET `message` = 70 WHERE `time` = 1681920000000
1000|2|2023-04-20 10:15:48 [W] sqlite > UPDATE `channel` SET `activity` = '{"19466":,"19467":50}' WHERE `id` = '477' AND `platform` = 'onebot'
1000|2|                            at f.handleError (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
1000|2|                            at c.run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:84:116)
1000|2|2023-04-20 10:15:48 [W] app Error: unable to open database file
1000|2|                            at c.step (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:81:)
1000|2|                            at SQLiteDriver.#exec (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::20)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::80
1000|2|                            at SQLiteDriver.#update (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::)
1000|2|                            at SQLiteDriver.#run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::41)
1000|2|                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
1000|2|                            at SQLiteDriver.upsert (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::51)
1000|2|                            at async DatabaseService.upsert (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:588:5)
1000|2|2023-04-20 10:15:49 [W] sqlite > UPDATE `user` SET `timers` = '{"_date":1682042077223,"marry":1681955682223,"jrrp":168195695}',`usage` = '{"_date":19467,"marry":1,"jrrp":1}',`lastCall` = 1681956948770 WHERE `id` = 3
1000|2|                            at f.handleError (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
1000|2|2023-04-20 10:15:49 [W] app Error: unable to open database file
1000|2|                            at c.run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:84:116)
1000|2|                            at c.step (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:81:)
1000|2|                            at SQLiteDriver.#exec (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::20)
1000|2|                            at C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::80
1000|2|                            at SQLiteDriver.#update (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::)
1000|2|                            at SQLiteDriver.#run (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::41)
1000|2|                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
1000|2|                            at SQLiteDriver.set (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js::49)
1000|2|                            at async DatabaseService.set (C:\Users\sergi\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:572:5)
```

### Launcher

Koishi Desktop

### Versions

- OS: Windows 10
- Adapter: QQ
- Node version: 16.19.1
- Koishi version: 4.12.5

**Comment by Seidko** [comment]
![image](https://user-images.githubusercontent.com/64234553/233552724-3c70065b-a94f-4a53-acc0-3275332e314a.png)
你的数据库文件打不开，检查一下有没有被锁定或者损坏。

**Comment by RightWhite** [comment]
我也出现这样的问题，重装系统后也还是这样的问题，我不知道该怎么搞了，其它插件是可以的，只有“娶群友”这个功能会反馈“未知错误”，大佬怎么破啊 0.0
![报错截图](https://github.com/koishijs/koishi-plugin-marry/assets/134984713/036733e1-15da-4eeb-b3ef-0773c5327e70)

**Comment by JstzjgscSergino** [comment]
> 

我也不知道……我已经退坑了。
QQ不让搞bot了……我倒是打算在discord上再搞一个，但到处是错误。实在是懒得折腾了。

**Comment by RightWhite** [comment]
> > 
> 
> 我也不知道……我已经退坑了。QQ 不让搞机器人了……我倒是打算在discord上再搞一个，但到处都是错误。实在是懒得折腾了。

现在QQ的风控已经解决了啊

**Comment by JstzjgscSergino** [comment]
> > > 
> > 
> > 
> > 我也不知道……我已经退坑了。QQ 不让搞机器人了……我倒是打算在discord上再搞一个，但到处都是错误。实在是懒得折腾了。
> 
> 现在QQ的风控已经解决了啊

啊？
（那为什么我在的群里bot还没启用，难道是管理人懒了……）

**Comment by RightWhite** [comment]
> > > > 
> > > 
> > > 
> > > 我也不知道……我已经退坑了。QQ不让搞机器人了……我倒是打算在discord上再搞一个，但到处都是错误。实在是懒得折腾了。
> > 
> > 
> > 现在QQ的风控已经解决了啊
> 
> 啊？ （那为什么我在机器人里还没有实现，顾是管理人懒了……）

你什么框架啊

**Comment by Seidko** [comment]
现在插件发布了 major 更新，可以更新测试一下？

**Comment by copurxia** [comment]
> 现在插件发布了 major 更新，可以更新测试一下？

major更新?

**Comment by copurxia** [comment]
> 现在插件发布了 major 更新，可以更新测试一下？

2.0.1仍然异常

**Comment by Seidko** [comment]
@copurxia 有无日志？

**Comment by copurxia** [comment]
> @copurxia 有无日志？

```bash
2023-09-28 16:53:02 [E] chronocat 插件所使用的 API 已无法再使用且已被移除。需要插件开发者更新插件以解决此问题。错误码：2014
2023-09-28 16:53:02 [W] command marry 
                        Error: 运行遇到错误。参考上一条日志以获得详细信息。
                            at Object.<anonymous> (/koishi/node_modules/@chronocat/koishi-plugin-adapter/lib/utils.js:6:24)
                            at Module._compile (node:internal/modules/cjs/loader:1256:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                            at Module.load (node:internal/modules/cjs/loader:1119:32)
                            at Module._load (node:internal/modules/cjs/loader:960:12)
                            at Module.require (node:internal/modules/cjs/loader:1143:19)
                            at require (node:internal/modules/cjs/helpers:121:18)
                            at Object.<anonymous> (/koishi/node_modules/@chronocat/koishi-plugin-adapter/lib/parser.js:7:17)
                            at Module._compile (node:internal/modules/cjs/loader:1256:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

**Comment by Seidko** [comment]
@copurxia 这是 chronocat 的问题，请等待 chronocat 支持
